"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Check, CircleCheck, Clock, Menu, X } from "lucide-react";
import { brand } from "../../config/brand";
import { IndustryResearch } from "./IndustryResearch";
import { PlatformStory } from "./PlatformStory";
import { ROICalculator } from "./ROICalculator";

const nav = [["Product", "problem"], ["How It Works", "how"], ["For Restaurants", "restaurants"], ["Training Demo", "preview"]];
const statements = ["Learn before the rush", "Reduce repeated explanations", "Build confident teams", "Entrena mejor", "Onboard consistently"];
const problems = [
  ["01", "Limited trainer availability", "Senior employees cannot step away from active service."],
  ["02", "Information overload", "New hires are expected to remember recipes, equipment, terminology, and procedures immediately."],
  ["03", "Paid but unproductive training", "Restaurants pay for long training shifts before employees can contribute independently."],
];
const steps = [
  { label: "Paso uno", title: "Build the training pathway", copy: "Managers turn the way their kitchen already works into a clear sequence for every new hire.", items: ["Restaurant orientation", "Safety and menu knowledge", "Cold station, fryer, and grill", "Opening and closing procedures"], image: brand.images.pathway, alt: "Chef reviewing plated food in a warm restaurant kitchen" },
  { label: "Paso dos", title: "Employees learn before their shift", copy: "Short, focused lessons make essential information easier to absorb before hands-on coaching begins.", items: ["Short videos", "Visual procedures and recipe guides", "Knowledge checks", "Pre-shift checklists"], image: brand.images.learning, alt: "Cook preparing colourful ingredients at a restaurant station" },
  { label: "Paso tres", title: "Managers track readiness", copy: "A practical overview helps leaders know who is learning, who needs support, and who is ready for the next station.", items: ["Module completion", "Quiz results and overdue training", "Station readiness", "Practical sign-offs"], image: brand.images.oversight, alt: "Restaurant manager reviewing training progress on a laptop" },
];

export function MarketingHome() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); onScroll(); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <>
    <header className={`marketing-nav ${scrolled ? "scrolled" : ""}`}>
      <div className="container nav-inner"><Link href="/" className="wordmark" aria-label={`${brand.name} home`}>{brand.name}.</Link>
        <nav className={`nav-links ${menuOpen ? "open" : ""}`} aria-label="Main navigation">{nav.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}</a>)}<Link href="/login" className="btn btn-primary">Explore the Demo</Link></nav>
        <button className="nav-toggle" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
      </div>
    </header>
    <main>
      <section className="hero" style={{ backgroundImage: `url(${brand.images.hero})` }}>
        <div className="container hero-content"><div><p className="eyebrow">Restaurant operations · Operaciones</p><h1 className="display">Train better. Waste less. Know what makes money.</h1><p className="hero-copy">{brand.name} connects employee learning, menu intelligence, and waste tracking—so independent restaurants can preserve knowledge and make everyday operating decisions with better context.</p><div className="hero-actions"><Link className="btn btn-primary" href="/login">Explore the Demo <ArrowRight size={18} /></Link></div></div>
          <div className="floating-progress"><div className="row between"><div className="row"><img className="avatar" src={brand.images.employee} alt={`Portrait of fictional employee ${brand.demoEmployee.name}`} /><div><strong>{brand.demoEmployee.name}</strong><div className="muted" style={{ fontSize: 13 }}>Cold Station Training</div></div></div><span className="tag">En curso</span></div><div className="row between" style={{ margin: "26px 0 10px" }}><strong>65% complete</strong><span className="muted">5 of 8</span></div><div className="progress"><span style={{ width: "65%" }} /></div><div className="row" style={{ marginTop: 20 }}><Clock size={17} /><span>Next shift: Tuesday, 4:00 PM</span></div></div>
        </div>
      </section>
      <div className="marquee" aria-label="Product benefits"><div className="marquee-track">{[...statements, ...statements].map((s, i) => <div className="marquee-item" key={`${s}${i}`}><span>{s}</span><i className="marquee-dot" /></div>)}</div></div>
      <section id="problem" className="section"><div className="container"><p className="eyebrow" style={{ color: "var(--chilli)" }}>The training gap</p><h2 className="display section-title">A busy shift should not be a new employee’s first lesson.</h2><p className="hero-copy muted" style={{ color: "var(--warm-grey)" }}>Restaurant training often happens while experienced employees are handling orders, preparing food, and managing rush periods. New hires either receive too little guidance or too much information at once.</p><div className="problem-grid">{problems.map(([n, t, c]) => <article className="card problem-card" key={n}><span className="problem-number">{n}</span><div><h3 className="display" style={{ fontSize: 28, marginBottom: 10 }}>{t}</h3><p className="muted">{c}</p></div></article>)}</div></div></section>
      <IndustryResearch />
      <PlatformStory />
      <ROICalculator />
      <section id="how" className="steps section"><div className="container"><p className="eyebrow" style={{ color: "var(--chilli)" }}>How {brand.name} works</p><h2 className="display section-title">From first login to first confident shift.</h2>{steps.map(step => <article className="step" key={step.title}><img className="step-image" src={step.image} alt={step.alt} /><div className="step-copy"><p className="eyebrow" style={{ color: "var(--chilli)" }}>{step.label}</p><h3 className="display">{step.title}</h3><p className="muted" style={{ lineHeight: 1.75 }}>{step.copy}</p><ul className="check-list">{step.items.map(item => <li key={item}><CircleCheck size={19} color="var(--chilli)" />{item}</li>)}</ul></div></article>)}</div></section>
      <section id="preview" className="preview-section section"><div className="container"><div className="row between" style={{ alignItems: "end", flexWrap: "wrap" }}><div><p className="eyebrow" style={{ color: "var(--chilli)" }}>Inside the product</p><h2 className="display section-title" style={{ maxWidth: 850 }}>Training that feels ready for the real world.</h2></div><Link className="btn btn-primary" href="/employee">Open Interactive Demo <ArrowRight size={18} /></Link></div><ProductPreview /></div></section>
      <section className="benefits section"><div className="container"><p className="eyebrow" style={{ color: "var(--tortilla)" }}>The result</p><h2 className="display section-title" style={{ maxWidth: 950 }}>Better preparation for employees. Less repetition for chefs.</h2><div className="benefit-grid">{["Faster onboarding", "More consistent training", "Better knowledge retention", "Reduced supervisory pressure"].map((x, i) => <article className="benefit" key={x}><span className="problem-number" style={{ color: "var(--tortilla)" }}>0{i + 1}</span><h3 className="display" style={{ fontSize: 29 }}>{x}</h3></article>)}</div></div></section>
      <section id="restaurants" className="section"><div className="container"><div style={{ maxWidth: 900 }}><p className="eyebrow" style={{ color: "var(--chilli)" }}>Built for independents</p><h2 className="display section-title">Structure without the corporate training machine.</h2><p className="muted" style={{ fontSize: 18, lineHeight: 1.8 }}>Large chains often have dedicated training platforms. Independent teams may rely on verbal instruction, paper documents, messaging apps, or shared files. {brand.name} brings those essentials into one simple, restaurant-shaped pathway.</p><div className="restaurant-types">{["Independent restaurants", "Restaurant groups", "Cafés", "Food trucks", "Catering teams", "Hospitality businesses"].map(x => <span key={x}>{x}</span>)}</div></div></div></section>
      <section className="knowledge-section section"><div className="container story-grid"><div><p className="eyebrow">Reusable restaurant knowledge</p><h2 className="display section-title">What if training knowledge didn&apos;t disappear every time someone left?</h2></div><div><p className="hero-copy" style={{color:"var(--charcoal)"}}>Restaurants cannot eliminate turnover, but they can make onboarding less dependent on manually transferring the same fundamentals every time. Digital learning supports—not replaces—paid practical coaching.</p><div className="onboarding-compare"><div><strong>Traditional onboarding</strong><p>Explain basics → rush interrupts → repeated questions → multiple supervised shifts → process starts over.</p></div><div><strong>baysics-assisted</strong><p>Assign pathway → confirm knowledge → coach execution → sign off competency → reuse the content.</p></div></div></div></div></section>
    </main>
    <footer className="marketing-footer"><div className="container"><div className="row between" style={{ flexWrap: "wrap", alignItems: "start" }}><div><div className="wordmark">{brand.name}.</div><p style={{ opacity: .65 }}>{brand.tagline}</p></div><div className="row" style={{ flexWrap: "wrap" }}><Link href="/login">Demo</Link><Link href="/employee">Employee</Link><Link href="/manager">Manager</Link><a href={`mailto:${brand.contactEmail}`}>Contact</a><span>Privacy</span><span>Terms</span></div></div><p className="display footer-big">Learn first.<br />Practise second.</p></div></footer>
  </>;
}

function ProductPreview() { return <div className="browser-frame"><div className="browser-top"><span /><span /><span /></div><div className="mini-dashboard"><aside className="mini-side"><div className="wordmark">{brand.name}.</div>{["Home", "My Training", "Recipes", "Checklists"].map(x => <div key={x} style={{ padding: "13px 0", opacity: x === "Home" ? 1 : .55, fontWeight: 800 }}>{x}</div>)}</aside><div className="mini-main"><p className="eyebrow" style={{ color: "var(--chilli)" }}>Bienvenido, {brand.demoEmployee.firstName}</p><h3 className="display" style={{ fontSize: 42, margin: "5px 0 25px" }}>Ready for your next station?</h3><div className="mini-grid"><div><div className="panel" style={{ background: "var(--cactus)", color: "white" }}><span className="tag" style={{ color: "var(--charcoal)" }}>Cold Station</span><h4 className="display" style={{ fontSize: 34, margin: "18px 0" }}>Cold Station Fundamentals</h4><div className="row between"><span>65% complete</span><span>18 min left</span></div><div className="progress" style={{ marginTop: 10 }}><span style={{ width: "65%" }} /></div></div><div className="panel" style={{ marginTop: 15 }}><strong>Training pathway</strong>{["Orientation", "Kitchen Safety", "Menu Knowledge"].map(x => <div className="row" style={{ marginTop: 15 }} key={x}><Check size={18} color="var(--agave)" /><span>{x}</span></div>)}</div></div><div className="panel"><p className="eyebrow">Próximo turno</p><h4 className="display" style={{ fontSize: 30 }}>Tuesday<br />4:00 PM</h4><p className="muted">Cold Station<br />Trainer: {brand.demoManager.name}</p><hr style={{ border: "0", borderTop: "1px solid var(--clay)" }} /><strong>Quiz: 88%</strong><p className="muted">Recently completed</p></div></div></div></div></div> }
