import Link from "next/link";
import { ArrowLeft, ClipboardCheck } from "lucide-react";
import { brand } from "../../config/brand";

const groups=[
  ["Training",["Time until independent station work","Trainer hours per employee","Quiz and training completion","Repeated foundational questions","Practical sign-off time"]],
  ["Retention",["30-day retention","60-day retention","90-day retention","Context on compensation, culture and scheduling"]],
  ["Menu",["Units sold","Item revenue","Plate cost","Food cost percentage","Contribution margin"]],
  ["Waste",["Waste quantity and cost","Reason and station","Ingredient and menu item","Day and service period"]],
] as const;
export function PilotDashboard(){return <main className="pilot-page"><header className="pilot-page-nav"><Link href="/" className="wordmark">{brand.name}.</Link><Link href="/" className="btn btn-light"><ArrowLeft size={17}/> Back to website</Link></header><section className="pilot-hero"><div><p className="eyebrow">Restaurant pilot framework</p><h1 className="display">What would we measure in a restaurant pilot?</h1><p>Start with a baseline, introduce the platform, and compare operational signals without pretending one tool caused every outcome.</p></div></section><section className="container section"><div className="pilot-measures">{groups.map(([title,items])=><article className="panel" key={title}><span className="icon-box"><ClipboardCheck/></span><h2 className="display">{title}</h2>{items.map(x=><p key={x}>{x}</p>)}</article>)}</div><div className="pilot-comparison"><div><p className="eyebrow">Before baysics</p><h2 className="display">Baseline</h2>{["Trainer hours","Time to sign-off","Waste cost","Menu contribution"].map(x=><p key={x}><span>{x}</span><strong>Pilot data required</strong></p>)}</div><div><p className="eyebrow">During baysics</p><h2 className="display">Observed period</h2>{["Trainer hours","Time to sign-off","Waste cost","Menu contribution"].map(x=><p key={x}><span>{x}</span><strong>Pilot data required</strong></p>)}</div></div><aside className="demo-notice"><strong>Measurement note:</strong> Retention and operating results have many causes. A pilot can identify patterns and associations, but does not establish that baysics caused an improvement by itself.</aside><div className="final-cta"><p className="eyebrow">Build the baseline first</p><h2 className="display">Measure honestly. Improve deliberately.</h2><Link href="/#pilot" className="btn btn-primary">Request a Pilot</Link></div></section></main>}
