import Link from "next/link";
import { ArrowRight, BarChart3, GraduationCap, Trash2 } from "lucide-react";

const pillars=[
  {icon:<GraduationCap/>,label:"TRAIN",title:"Give people the knowledge before they need it under pressure.",items:["Employee pathways","Videos and quizzes","Recipes and SOPs","Certifications and sign-offs"],href:"/employee"},
  {icon:<BarChart3/>,label:"UNDERSTAND",title:"Know what sells—and whether it actually makes money.",items:["Sales mix","Plate cost","Contribution margin","Menu classifications"],href:"/manager/menu-engineering"},
  {icon:<Trash2/>,label:"REDUCE",title:"See what you throw away in dollars, not just kilograms.",items:["Waste logging","Reasons and trends","Ingredient losses","Menu-item impact"],href:"/manager/waste"},
];
export function PlatformStory(){return <><section className="platform-section section" id="platform"><div className="container"><p className="eyebrow" style={{color:"var(--chilli)"}}>Restaurant operations, connected</p><h2 className="display section-title">One restaurant. Three systems that should talk to each other.</h2><div className="pillar-grid">{pillars.map(p=><article key={p.label}><span className="pillar-icon">{p.icon}</span><p className="eyebrow">{p.label}</p><h3 className="display">{p.title}</h3>{p.items.map(x=><span key={x}>{x}</span>)}<Link href={p.href}>Explore {p.label.toLowerCase()} <ArrowRight size={17}/></Link></article>)}</div><div className="system-flow" aria-label="Connected product cycle"><strong>TRAIN</strong><i>→</i><strong>EXECUTE</strong><i>→</i><strong>MEASURE</strong><i>→</i><strong>IMPROVE</strong></div></div></section><section className="operations-story section"><div className="container"><p className="eyebrow">From knowledge to operating intelligence</p><div className="story-flow">{["A new employee is hired","Structured training is assigned","They learn the menu and station","Knowledge checks confirm comprehension","Hands-on coaching begins","Managers sign off competency","Waste and production are logged","Menu costs meet operating losses","Managers identify opportunities"].map((step,index)=><div key={step}><span>{String(index+1).padStart(2,"0")}</span><strong>{step}</strong></div>)}</div><h2 className="display">Training becomes operational intelligence.</h2></div></section></>}
