"use client";

import { useMemo, useState } from "react";
import { Clock, Printer, Search, X } from "lucide-react";
import { recipes } from "../../data/mock-data";
import type { Recipe } from "../../types";

export function RecipesPage(){const [query,setQuery]=useState("");const [selected,setSelected]=useState<Recipe|null>(null);const filtered=useMemo(()=>recipes.filter(r=>`${r.name} ${r.spanishName} ${r.station}`.toLowerCase().includes(query.toLowerCase())),[query]);return <><div className="section-head"><div><p className="eyebrow" style={{color:"var(--chilli)"}}>Recetas y preparación</p><h1 className="display">Recipe guides</h1><p className="muted">Search demonstration cards by recipe, Spanish name, or station.</p></div><label className="row" style={{position:"relative"}}><Search size={18} style={{position:"absolute",left:16}}/><span className="sr-only">Search recipes</span><input className="search" style={{paddingLeft:45}} placeholder="Search recipes…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{filtered.length?<div className="recipe-grid">{filtered.map(recipe=><article className="card recipe-card" key={recipe.id}><img src={recipe.image} alt={`${recipe.name} demonstration placeholder`}/><div className="card-body"><span className="tag">{recipe.station}</span><h2>{recipe.name}</h2><p className="muted">{recipe.spanishName}</p><div className="recipe-meta"><span className="tag"><Clock size={13}/>{recipe.time}</span><span className="tag">{recipe.difficulty}</span><span className="tag">{recipe.allergens.length?recipe.allergens.join(", "):"No listed allergens"}</span></div><div className="row between"><strong>{recipe.status}</strong><button className="btn btn-outline" onClick={()=>setSelected(recipe)}>View Guide</button></div></div></article>)}</div>:<div className="panel" style={{textAlign:"center",padding:60}}><h2 className="display">No recipe guides found</h2><p className="muted">Try a different recipe or station name.</p></div>}{selected&&<RecipeModal recipe={selected} close={()=>setSelected(null)}/>}</>}

function RecipeModal({recipe,close}:{recipe:Recipe;close:()=>void}){return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&close()}><article className="modal" role="dialog" aria-modal="true" aria-labelledby="recipe-title"><button className="round-btn close no-print" onClick={close} aria-label="Close recipe guide"><X/></button><img src={recipe.image} alt={`${recipe.name} demonstration dish`} style={{width:"100%",height:280,objectFit:"cover",borderRadius:18}}/><p className="eyebrow" style={{color:"var(--chilli)",marginTop:25}}>Placeholder demonstration recipe</p><h2 id="recipe-title" className="display" style={{fontSize:48,margin:"8px 0"}}>{recipe.name}</h2><p className="muted" style={{fontSize:18}}>{recipe.spanishName}</p><div className="row" style={{flexWrap:"wrap"}}><span className="tag">{recipe.station}</span><span className="tag">{recipe.time}</span><span className="tag">{recipe.difficulty}</span></div><div className="mini-grid" style={{marginTop:30}}><section><h3 className="display" style={{fontSize:28}}>Ingredients</h3><ul>{recipe.ingredients.map(x=><li key={x}>{x}</li>)}</ul></section><section><h3 className="display" style={{fontSize:28}}>Equipment</h3><ul>{recipe.equipment.map(x=><li key={x}>{x}</li>)}</ul></section></div><h3 className="display" style={{fontSize:28}}>Numbered method</h3><ol>{recipe.method.map((x,i)=><li key={x} style={{marginBottom:12}}><strong>{i+1}.</strong> {x}</li>)}</ol><div className="panel" style={{marginTop:25}}><p><strong>Portion:</strong> {recipe.portion}</p><p><strong>Quality:</strong> {recipe.quality}</p><p><strong>Storage:</strong> {recipe.storage}</p><p><strong>Allergens:</strong> {recipe.allergens.length?recipe.allergens.join(", "):"None listed in demo"}</p><p><strong>Manager notes:</strong> {recipe.notes}</p></div><div className="warning" style={{marginTop:20}}>This is placeholder product-demo material. Confirm all live ingredients, allergens, food-safety information, portions, temperatures, and methods with the restaurant.</div><button className="btn btn-dark no-print" onClick={()=>window.print()} style={{marginTop:20}}><Printer size={17}/> Print Guide</button></article></div>}
