"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { Award, BarChart3, Bell, BookOpen, Building2, ChartNoAxesCombined, ChefHat, ClipboardCheck, FileText, Home, Library, Menu, PackageOpen, Settings, Trash2, Users, X } from "lucide-react";
import { brand } from "../../config/brand";

const employeeNav = [["Home","/employee",Home],["Training","/employee/training",BookOpen],["Menu Knowledge","/employee/menu-knowledge",FileText],["Recipes","/employee/recipes",ChefHat],["Station Guides","/employee/training",Library],["Checklists","/employee/checklists",ClipboardCheck],["Certificates","/employee/certificates",Award]] as const;
const managerNav = [["Overview","/manager",ChartNoAxesCombined],["Team","/manager/employees",Users],["Training","/manager/content",BookOpen],["Menu Engineering","/manager/menu-engineering",BarChart3],["Waste","/manager/waste",Trash2],["Recipes","/employee/recipes",ChefHat],["Reports","/manager",PackageOpen],["Settings","/manager",Settings]] as const;

export function AppShell({role,children}: {role:"employee"|"manager";children:React.ReactNode}){
  const path=usePathname(); const [open,setOpen]=useState(false); const items=role==="employee"?employeeNav:managerNav;
  return <div className="app-layout"><aside className={`sidebar ${open?"open":""}`}><div className="row between"><Link href="/" className="wordmark">{brand.name}.</Link><button className="round-btn mobile-menu-btn" onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button></div><nav className="sidebar-nav" aria-label={`${role} navigation`}>{items.map(([label,href,Icon],index)=><Link key={label} href={href} onClick={()=>setOpen(false)} className={`side-link ${(index===0?path===href:path.startsWith(href)&&href!==`/${role}`)?"active":""}`}><Icon size={19}/>{label}</Link>)}</nav><div className="side-user">{role==="employee"?<div className="row"><img src={brand.images.employee} className="avatar" alt={`Portrait of fictional employee ${brand.demoEmployee.name}`}/><div><strong style={{fontSize:13}}>{brand.demoEmployee.name}</strong><div style={{fontSize:11,opacity:.6}}>{brand.demoEmployee.role} · {brand.restaurantName}</div></div></div>:<div className="row"><span className="icon-box"><Building2 size={20}/></span><div><strong style={{fontSize:13}}>{brand.demoManager.name}</strong><div style={{fontSize:11,opacity:.6}}>{brand.demoManager.role}</div></div></div>}</div></aside><main className="app-main"><header className="app-header"><div className="row"><button className="round-btn mobile-menu-btn" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu/></button><div><p className="eyebrow" style={{color:"var(--chilli)",margin:0}}>{role==="employee"?"Bienvenido":"Panel de gerente"}</p><strong>{role==="employee"?`Good morning, ${brand.demoEmployee.firstName}.`:`Good morning, ${brand.demoManager.firstName}.`}</strong></div></div><div className="header-actions"><select aria-label="Restaurant location" defaultValue="main"><option value="main">{brand.restaurantName}</option></select><span className="tag header-role">{role==="employee"?"Employee Demo":"Manager Demo"}</span><button className="round-btn" aria-label="Notifications"><Bell size={19}/></button></div></header><div className="app-content">{children}</div></main>{open&&<button aria-label="Close navigation overlay" onClick={()=>setOpen(false)} style={{position:"fixed",inset:0,zIndex:30,border:0,background:"rgba(0,0,0,.35)"}}/>}</div>
}
