"use client";

import Link from "next/link";
import { useState } from "react";
import { Archive, BookOpen, CheckSquare, Copy, Edit3, Eye, FileQuestion, Plus, Utensils, Video, X } from "lucide-react";

const initialItems=[
  {title:"Restaurant Orientation",type:"Modules",detail:"5 lessons · Published",icon:BookOpen},{title:"Cold Station Setup",type:"Lessons",detail:"7 min · Video + text",icon:Video},{title:"Guacamole Preparation",type:"Recipes",detail:"Cold Station · Published",icon:Utensils},{title:"Fryer Safety Check",type:"Quizzes",detail:"5 questions · 80% pass",icon:FileQuestion},{title:"Opening the Cold Station",type:"Checklists",detail:"4 items · Required",icon:CheckSquare},
];
const tabs=["Modules","Lessons","Recipes","Quizzes","Checklists"];
export function ContentLibrary(){const [tab,setTab]=useState("Modules");const [editor,setEditor]=useState(false);const [items,setItems]=useState(initialItems);const visible=items.filter(i=>i.type===tab);const duplicate=(title:string)=>setItems(current=>[...current,{...current.find(i=>i.title===title)!,title:`${title} (Copy)`}]);return <><div className="section-head"><div><p className="eyebrow" style={{color:"var(--chilli)"}}>Biblioteca</p><h1 className="display">Training content</h1><p className="muted">Organize the restaurant’s learning pathway in one place.</p></div><div className="row"><button className="btn btn-outline" onClick={()=>setEditor(true)}><Plus size={17}/> Add Lesson</button><button className="btn btn-primary" onClick={()=>setEditor(true)}><Plus size={17}/> Add Module</button></div></div><section className="panel"><div className="tabs" role="tablist">{tabs.map(x=><button role="tab" aria-selected={tab===x} className={`tab ${tab===x?"active":""}`} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{visible.length?visible.map(item=>{const Icon=item.icon;return <div className="content-row" key={item.title}><span className="icon-box"><Icon size={19}/></span><div><strong>{item.title}</strong><div className="muted" style={{fontSize:13}}>{item.detail}</div></div><div className="row"><button className="round-btn" title="Duplicate" onClick={()=>duplicate(item.title)}><Copy size={17}/></button><button className="round-btn" title="Edit" onClick={()=>setEditor(true)}><Edit3 size={17}/></button><button className="round-btn" title="Archive"><Archive size={17}/></button><Link className="round-btn" title="Preview as employee" href="/employee/training"><Eye size={17}/></Link></div></div>}):<div style={{textAlign:"center",padding:60}}><h2 className="display">No {tab.toLowerCase()} yet</h2><button className="btn btn-primary" onClick={()=>setEditor(true)}>Add first item</button></div>}</section>{editor&&<Editor close={()=>setEditor(false)}/>}</>}
function Editor({close}:{close:()=>void}){return <div className="drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="editor-title"><button className="round-btn close" onClick={close} aria-label="Close lesson editor"><X/></button><p className="eyebrow" style={{color:"var(--chilli)"}}>Content editor</p><h2 id="editor-title" className="display" style={{fontSize:48,margin:"5px 0 25px"}}>Edit lesson</h2><form className="login-form" onSubmit={e=>{e.preventDefault();close()}}><div className="field"><label htmlFor="lesson-title">Title</label><input id="lesson-title" defaultValue="Cold Station Setup"/></div><div className="field"><label htmlFor="station">Station</label><select id="station"><option>Cold Station</option><option>Fryer</option><option>Grill</option><option>Orientation</option></select></div><div className="field"><label htmlFor="description">Description</label><textarea id="description" rows={3} defaultValue="Introduce the station layout, tools, and opening flow."/></div><div className="field"><label htmlFor="video-url">Video URL</label><input id="video-url" placeholder="https://video.example/lesson"/></div><div className="field"><label htmlFor="lesson-content">Lesson content</label><textarea id="lesson-content" rows={8} defaultValue="Add visual instructions, quality references, terminology, and manager notes here."/></div><div className="field"><label htmlFor="duration">Estimated duration</label><input id="duration" type="number" defaultValue="7"/></div><label className="check-item"><input type="checkbox" defaultChecked/> Quiz required</label><label className="check-item"><input type="checkbox" defaultChecked/> Required before first shift</label><div className="row"><button type="button" className="btn btn-outline" onClick={close}>Cancel</button><button className="btn btn-primary" type="submit">Save Demo Lesson</button></div></form></aside></div>}
