"use client";

import { useMemo, useState } from "react";
import { ArrowDownUp, X } from "lucide-react";
import { menuAnalytics, menuTotals } from "../../data/menu-analytics";
import { menuMetadata } from "../../data/alimentaria-menu";
import type { MenuItemAnalytics } from "../../types";
import { DemoDataBadge, DemoNotice, InsightCard, MetricCard } from "../shared/OperationsUI";

const money = new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",maximumFractionDigits:0});
const exactMoney = new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"});
type SortKey = "name"|"unitsSold"|"revenue"|"foodCostPercent"|"contributionMargin";

export function MenuEngineering(){
  const [category,setCategory]=useState("All"); const [classification,setClassification]=useState("All"); const [sort,setSort]=useState<SortKey>("revenue"); const [selected,setSelected]=useState<MenuItemAnalytics|null>(null);
  const items=useMemo(()=>menuAnalytics.filter(item=>(category==="All"||item.category===category)&&(classification==="All"||item.classification===classification)).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):(b[sort] as number)-(a[sort] as number)),[category,classification,sort]);
  const topSeller=[...menuAnalytics].sort((a,b)=>b.unitsSold-a.unitsSold)[0]; const highMargin=[...menuAnalytics].sort((a,b)=>b.contributionMargin-a.contributionMargin)[0]; const lowMargin=[...menuAnalytics].sort((a,b)=>a.contributionMargin-b.contributionMargin)[0];
  return <><div className="section-head"><div><p className="eyebrow" style={{color:"var(--chilli)"}}>Understand · Entender</p><h1 className="display">Menu Engineering</h1><p className="muted">Understand what&apos;s selling, what it&apos;s costing, and what deserves a second look.</p></div><DemoDataBadge/></div><DemoNotice/>
  <div className="metric-grid"><MetricCard label="Demo revenue" value={money.format(menuTotals.revenue)}/><MetricCard label="Average food cost" value={`${(menuTotals.cost/menuTotals.revenue*100).toFixed(1)}%`}/><MetricCard label="Highest selling" value={topSeller.name} detail={`${topSeller.unitsSold} demo units`}/><MetricCard label="Highest margin" value={highMargin.name} detail={exactMoney.format(highMargin.contributionMargin)}/><MetricCard label="Lowest margin" value={lowMargin.name} detail={exactMoney.format(lowMargin.contributionMargin)}/><MetricCard label="Estimated waste" value={money.format(menuTotals.waste)} detail="Allocated demo cost"/></div>
  <section className="panel matrix-panel"><div className="row between"><div><p className="eyebrow muted">Popularity × margin</p><h2 className="panel-title">Menu engineering matrix</h2></div><span className="tag">Click any item</span></div><div className="menu-matrix" aria-label="Four quadrant menu engineering matrix. High popularity is to the right and high contribution margin is toward the top."><span className="axis-y">Higher margin</span><span className="axis-x">Higher popularity →</span>{["puzzle","star","dog","plowhorse"].map(value=><div className={`quadrant ${value}`} key={value}><strong>{value}s</strong><small>{value==="star"?"Popular + profitable":value==="plowhorse"?"Popular + lower margin":value==="puzzle"?"Profitable + less popular":"Lower popularity + margin"}</small></div>)}{menuAnalytics.map(item=><button key={item.id} className={`matrix-point ${item.classification}`} style={{left:`${12+item.popularityScore*.76}%`,bottom:`${8+Math.min(76,item.contributionMargin*3.2)}%`}} onClick={()=>setSelected(item)} aria-label={`Open ${item.name}, ${item.classification}`} title={item.name}>{item.name.split(" ").map(x=>x[0]).join("").slice(0,3)}</button>)}</div><p className="muted chart-summary">The matrix classifies fictional sales and cost performance. Public item names and prices come from the cited menu.</p></section>
  <div className="manager-grid ops-insights"><InsightCard title="Popular, lower-margin items">Guacamole and select high-volume items deserve portion-cost and pricing review—not automatic changes.</InsightCard><InsightCard title="High-margin opportunities">Promote puzzle items through menu placement, descriptions, or staff recommendations and observe results.</InsightCard></div>
  <section className="panel"><div className="row between table-toolbar"><div><p className="eyebrow muted">Public menu + demo operations</p><h2 className="panel-title">Item performance</h2></div><div className="filters"><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Filter by category"><option>All</option>{[...new Set(menuAnalytics.map(i=>i.category))].map(x=><option key={x}>{x}</option>)}</select><select value={classification} onChange={e=>setClassification(e.target.value)} aria-label="Filter by classification"><option>All</option>{["star","plowhorse","puzzle","dog"].map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value as SortKey)} aria-label="Sort menu items"><option value="revenue">Revenue</option><option value="unitsSold">Units sold</option><option value="contributionMargin">Margin</option><option value="foodCostPercent">Food cost</option><option value="name">Name</option></select></div></div><div className="table-wrap"><table className="data-table menu-table"><thead><tr>{["Item","Category","Menu price","Units","Revenue","Plate cost","Food cost","Margin","Waste","Class","Action"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.category}</td><td>{item.priceDisplay}</td><td>{item.unitsSold}</td><td>{money.format(item.revenue)}</td><td>{exactMoney.format(item.foodCostPerPlate)}</td><td>{item.foodCostPercent.toFixed(1)}%</td><td>{exactMoney.format(item.contributionMargin)}</td><td>{exactMoney.format(item.allocatedWasteCost*item.unitsSold)}</td><td><span className={`classification ${item.classification}`}>{item.classification}</span></td><td><button className="btn-link" onClick={()=>setSelected(item)}>View</button></td></tr>)}</tbody></table></div><div className="source-citation"><ArrowDownUp size={17}/><div><strong>{menuMetadata.menuSource}</strong> · verified {menuMetadata.verified}. <a href={menuMetadata.menuSourceUrl} target="_blank" rel="noreferrer">View source menu</a>. All operational metrics are fictional.</div></div></section>
  {selected&&<ItemDrawer item={selected} close={()=>setSelected(null)}/>}</>;
}

function ItemDrawer({item,close}:{item:MenuItemAnalytics;close:()=>void}){return <div className="drawer-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="item-title"><button className="round-btn close" onClick={close} aria-label="Close item details"><X/></button><DemoDataBadge/><h2 id="item-title" className="display drawer-title">{item.name}</h2><p className="muted">{item.description}</p><div className="drawer-metrics"><MetricCard label="Public menu price" value={item.priceDisplay}/><MetricCard label="Demo units sold" value={`${item.unitsSold}`}/><MetricCard label="Demo revenue" value={money.format(item.revenue)}/><MetricCard label="Food cost" value={`${item.foodCostPercent.toFixed(1)}%`}/></div><h3>Profitability before and after waste</h3><div className="cost-bridge"><div><span>Plate cost</span><strong>{exactMoney.format(item.foodCostPerPlate)}</strong></div><div><span>Margin before waste</span><strong>{exactMoney.format(item.contributionMargin)}</strong></div><div><span>Waste per serving</span><strong>{exactMoney.format(item.allocatedWasteCost)}</strong></div><div><span>Adjusted margin</span><strong>{exactMoney.format(item.adjustedContributionMargin)}</strong></div></div><h3>Illustrative recipe-cost model</h3><p className="muted">Generic categories only—these are not the restaurant&apos;s recipe quantities or vendor costs.</p>{item.ingredientCosts.map(x=><div className="ingredient-row" key={x.ingredient}><span>{x.ingredient}</span><strong>{exactMoney.format(x.cost)}</strong></div>)}<InsightCard title={`${item.classification} opportunity`}>{item.classification==="star"?"Protect consistency and monitor waste on this strong performer.":item.classification==="plowhorse"?"Review portion cost or pricing while preserving guest value.":item.classification==="puzzle"?"Test menu placement and staff recommendations.":"Review whether the item earns its operational complexity."}</InsightCard></aside></div>}
