"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Plus, Trash2 } from "lucide-react";
import { initialWasteLogs, wasteCost } from "../../data/waste-data";
import { publicMenu } from "../../data/alimentaria-menu";
import { readStorage, STORAGE_KEYS, writeStorage } from "../../lib/storage";
import type { WasteLog, WasteReason } from "../../types";
import { DemoDataBadge, DemoNotice, InsightCard, MetricCard } from "../shared/OperationsUI";

const money=new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"});
const reasons:WasteReason[]=["Over-prep","Spoilage","Incorrect preparation","Quality issue","Returned order","Dropped/damaged","Trim","Expired","Other"];
const colors=["#D85032","#E9A23B","#72865B","#26352B","#F2CB4D"];

export function WasteTracker(){
  const [logs,setLogs]=useState<WasteLog[]>(initialWasteLogs); const [showForm,setShowForm]=useState(false);
  useEffect(()=>{const storedLogs=readStorage(STORAGE_KEYS.waste,initialWasteLogs);queueMicrotask(()=>setLogs(storedLogs))},[]);
  const totals=useMemo(()=>{const byReason=new Map<string,number>();const byStation=new Map<string,number>();const byIngredient=new Map<string,number>();const byDate=new Map<string,number>();logs.forEach(log=>{const cost=wasteCost(log);byReason.set(log.reason,(byReason.get(log.reason)||0)+cost);byStation.set(log.station,(byStation.get(log.station)||0)+cost);byIngredient.set(log.ingredient,(byIngredient.get(log.ingredient)||0)+cost);byDate.set(log.date,(byDate.get(log.date)||0)+cost)});return {total:logs.reduce((sum,log)=>sum+wasteCost(log),0),today:logs.filter(x=>x.date==="2026-08-27").reduce((sum,x)=>sum+wasteCost(x),0),byReason:[...byReason].map(([name,value])=>({name,value})),byStation:[...byStation].map(([name,value])=>({name,value})),byIngredient:[...byIngredient].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value),byDate:[...byDate].sort().map(([date,value])=>({date:date.slice(5),value}))}},[logs]);
  const save=(next:WasteLog[])=>{setLogs(next);writeStorage(STORAGE_KEYS.waste,next)};
  return <><div className="section-head"><div><p className="eyebrow" style={{color:"var(--chilli)"}}>Reduce · Reducir</p><h1 className="display">Waste Tracker</h1><p className="muted">See what was thrown away, why it happened, and what it cost.</p></div><button className="btn btn-primary" onClick={()=>setShowForm(!showForm)}><Plus size={18}/> Log waste</button></div><DemoNotice/>{showForm&&<WasteForm onAdd={log=>{save([log,...logs]);setShowForm(false)}}/>}
  <div className="metric-grid"><MetricCard label="Waste cost today" value={money.format(totals.today)}/><MetricCard label="This week" value={money.format(totals.total)}/><MetricCard label="This month" value={money.format(totals.total*3.4)} detail="Illustrative projection"/><MetricCard label="% of demo food cost" value={`${(totals.total/13840*100).toFixed(2)}%`}/><MetricCard label="Top ingredient" value={totals.byIngredient[0]?.name||"No entries"}/><MetricCard label="Top station" value={[...totals.byStation].sort((a,b)=>b.value-a.value)[0]?.name||"No entries"}/></div>
  <div className="analytics-grid"><section className="panel"><h2 className="panel-title">Waste by reason</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={totals.byReason} dataKey="value" nameKey="name" innerRadius={55} outerRadius={92}>{totals.byReason.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(value)=>money.format(Number(value))}/></PieChart></ResponsiveContainer></div><ul className="chart-legend">{totals.byReason.map((x,i)=><li key={x.name}><i style={{background:colors[i%colors.length]}}/>{x.name}: {money.format(x.value)}</li>)}</ul></section><section className="panel"><h2 className="panel-title">Waste cost over time</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><LineChart data={totals.byDate}><CartesianGrid strokeDasharray="3 3" stroke="#e1d5c4"/><XAxis dataKey="date"/><YAxis/><Tooltip formatter={(value)=>money.format(Number(value))}/><Line type="monotone" dataKey="value" stroke="#D85032" strokeWidth={3}/></LineChart></ResponsiveContainer></div></section><section className="panel"><h2 className="panel-title">Waste by station</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={totals.byStation} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis dataKey="name" type="category" width={90}/><Tooltip formatter={(value)=>money.format(Number(value))}/><Bar dataKey="value" fill="#72865B" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></div></section><section className="panel"><h2 className="panel-title">Top wasted ingredients</h2><div className="rank-list">{totals.byIngredient.slice(0,6).map((x,i)=><div key={x.name}><span><b>{i+1}</b>{x.name}</span><strong>{money.format(x.value)}</strong></div>)}</div></section></div>
  <div className="manager-grid ops-insights"><InsightCard title="Cold Station needs review" action={<Link className="btn-link" href="/employee/training/cold-station">Open relevant training module →</Link>}>Cold Station has the highest logged demo waste. Review portioning training as one possible response—not a guaranteed fix.</InsightCard><InsightCard title="Over-preparation leads recorded causes">Adjust prep forecasts and continue logging outcomes before changing production standards.</InsightCard></div>
  <section className="panel"><div className="row between"><div><p className="eyebrow muted">Local demo log</p><h2 className="panel-title">Recent entries</h2></div><DemoDataBadge/></div><div className="waste-log-list">{logs.length?logs.map(log=><article key={log.id}><div><strong>{log.ingredient}</strong><p>{log.quantity} {log.unit} · {log.station} · {log.reason}</p><small>{log.date} at {log.time} · {log.employee}{log.note?` · ${log.note}`:""}</small></div><div><strong>{money.format(wasteCost(log))}</strong><button className="round-btn" onClick={()=>save(logs.filter(x=>x.id!==log.id))} aria-label={`Delete ${log.ingredient} waste entry`}><Trash2 size={16}/></button></div></article>):<div className="empty-state">No waste entries yet. Log the first item to begin the demo.</div>}</div></section></>;
}

function WasteForm({onAdd}:{onAdd:(log:WasteLog)=>void}){function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);onAdd({id:crypto.randomUUID(),date:String(data.get("date")),time:String(data.get("time")),ingredient:String(data.get("ingredient")),menuItemId:String(data.get("menuItem"))||undefined,quantity:Number(data.get("quantity")),unit:String(data.get("unit")),unitCost:Number(data.get("unitCost")),station:String(data.get("station")),employee:String(data.get("employee")),reason:String(data.get("reason")) as WasteReason,note:String(data.get("note")),provenance:"illustrative-demo"})}return <form className="panel waste-form" onSubmit={submit}><div className="row between"><h2 className="panel-title">Log daily waste</h2><DemoDataBadge/></div><label>Date<input name="date" type="date" defaultValue="2026-08-27" required/></label><label>Time<input name="time" type="time" defaultValue="16:00" required/></label><label>Ingredient<input name="ingredient" placeholder="e.g. Avocado" required/></label><label>Menu item<select name="menuItem"><option value="">Not linked</option>{publicMenu.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Unit<select name="unit"><option>kg</option><option>each</option><option>litre</option><option>portion</option></select></label><label>Estimated unit cost<input name="unitCost" type="number" min="0" step="0.01" required/></label><label>Station<select name="station"><option>Cold Station</option><option>Fryer</option><option>Grill</option><option>Bar</option><option>Prep</option></select></label><label>Employee<input name="employee" defaultValue="Bhavik" required/></label><label>Reason<select name="reason">{reasons.map(x=><option key={x}>{x}</option>)}</select></label><label className="full">Note<textarea name="note" rows={3}/></label><button className="btn btn-dark full" type="submit">Save waste entry</button></form>}
