"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, CheckCircle2, RotateCcw, XCircle } from "lucide-react";
import { quizQuestions } from "../../data/mock-data";
import { readStorage, STORAGE_KEYS, writeStorage } from "../../lib/storage";

export function QuizExperience(){
  const [index,setIndex]=useState(0);const [selected,setSelected]=useState("");const [checked,setChecked]=useState(false);const [correct,setCorrect]=useState(0);const [done,setDone]=useState(false);const q=quizQuestions[index];
  const submit=()=>{if(!selected)return;setChecked(true);if(selected===q.answer)setCorrect(v=>v+1)};
  const next=()=>{if(index===quizQuestions.length-1){const score=Math.round((correct/quizQuestions.length)*100);const results=readStorage<Record<string,number>>(STORAGE_KEYS.quiz,{});writeStorage(STORAGE_KEYS.quiz,{...results,fryer:score});window.dispatchEvent(new Event("mise-storage"));setDone(true)}else{setIndex(v=>v+1);setSelected("");setChecked(false)}};
  const reset=()=>{setIndex(0);setSelected("");setChecked(false);setCorrect(0);setDone(false)};
  if(done){const score=Math.round((correct/quizQuestions.length)*100);const passed=score>=80;return <div className="quiz-shell"><div className="card quiz-question" style={{textAlign:"center"}}>{passed?<CheckCircle2 size={65} color="var(--agave)"/>:<XCircle size={65} color="var(--chilli)"/>}<p className="eyebrow" style={{marginTop:20}}>{passed?"Knowledge check passed":"Review recommended"}</p><h1 className="display" style={{fontSize:70,margin:"10px 0"}}>{score}%</h1><p className="muted">You answered {correct} of {quizQuestions.length} questions correctly.</p><div className="hero-actions" style={{justifyContent:"center"}}><button className="btn btn-outline" onClick={reset}><RotateCcw size={17}/> Retake Quiz</button><Link className="btn btn-primary" href="/employee">Continue Training <ArrowRight size={17}/></Link></div></div></div>}
  const isCorrect=selected===q.answer;
  return <div className="quiz-shell"><div className="row between"><div><p className="eyebrow" style={{color:"var(--chilli)"}}>Fryer station knowledge check</p><h1 className="display app-title">Question {index+1} of {quizQuestions.length}</h1></div><strong>{Math.round((index/quizQuestions.length)*100)}%</strong></div><div className="progress" style={{marginTop:20}}><span style={{width:`${((index+1)/quizQuestions.length)*100}%`}}/></div><section className="card quiz-question"><span className="tag">{q.type==="image"?"Image selection placeholder":q.type.replace("multiple","Multiple choice")}</span><h2 className="display" style={{fontSize:34,margin:"25px 0"}}>{q.prompt}</h2><div className="answer-list">{q.options.map(option=>{let cls=selected===option?"selected":"";if(checked&&option===q.answer)cls="correct";else if(checked&&selected===option)cls="incorrect";return <button key={option} className={`answer ${cls}`} onClick={()=>!checked&&setSelected(option)} disabled={checked}>{option}</button>})}</div>{checked&&<div className="feedback"><div className="row">{isCorrect?<CheckCircle2 color="var(--agave)"/>:<XCircle color="var(--chilli)"/>}<strong>{isCorrect?"Correct":"Not quite"}</strong></div><p>{q.explanation}</p></div>}<div className="row between" style={{marginTop:25}}><span className="muted">Select one answer</span>{!checked?<button className="btn btn-dark" onClick={submit} disabled={!selected}>Submit answer</button>:<button className="btn btn-primary" onClick={next}>{index===quizQuestions.length-1?"See result":"Next question"}<ArrowRight size={17}/></button>}</div></section></div>;
}
